### ISSUE TITLE
DesiredCapabilities not getting picked up properly

### ISSUE THREAD

**Issue by jpchanson** [jpchanson/BeSeenium#17]
on the remoteDriver the capabilities arnt being loaded correctly so the driver uses its default values. This needs fixing before browserStack integration becomes useful.

**Comment by jpchanson** [comment]
after refactoring the ActionDataFactory again, the capabilities now work.

changed from using reflection (horrible and ugly), to a implkementing a 'MakeActionData' class hierarchy(the sensible way which I should have thought of first)

**Comment by iamjonjackson** [comment]
Whoop!

--
Regards,
Jon
